export { default as StatisticsTabletText } from './StatisticsTabletText.styled';
export { default as StatisticsContainerTablet } from './StatisticsContainerTablet.styled';
export { default as StatisticsButton } from './StatisticsButton.styled';
export { default as StatisticsContainerCommon } from './StatisticsContainerCommon.styled';
export { default as StatInput } from './StatInput.styled';
export { default as StatSubContainer } from './StatSubContainer.styled';
export { default as StatLabel } from './StatLabel.styled';
export { default as StatCommonContainer } from './StatCommonContainer.styled';
export { default as StatTable } from './StatTable.styled';
export { default as StatPagesContainer } from './StatPagesContainer.styled';
export { default as StatSubContainerTable } from './StatSubContainerTable.styled';
export { default as StatTableDate } from './StatTableDate.styled';
export { default as StatTableTime } from './StatTableTime.styled';
export { default as StatTableTextPage } from './StatTableTextPage.styled';
export { default as StatTextResolt } from './StatTextResolt.styled';
export { default as StatTableScroll } from './StatTableScroll.styled';
export {BoxStatGoals, BoxStatGoalsDesctop, BoxStatDesctop, BoxGoalsDesctop} from './BoxStatGoals.styled';
