export { default as ModalTitle } from './ModalTitle.styled';
export { default as ModalWripper } from './ModalWripper.styled';
export { default as RaitingBlok } from './RaitingBlok.styled';
export { default as RaitingStar } from './RaitingStar.styled';
export { default as ResumeTitle } from './ResumeTitle.styled';
export { default as InputModal } from './InputModal.styled';
export { default as ButtonBlock } from './ButtonBlock.styled';
export { default as ButtonModal } from './ButtonModal.styled';
export { default as ConteinerModal } from './ConteinerModal.styled';
